### ISSUE TITLE
graphql-kotlin-ktor-client locked on old version of ktor

### ISSUE THREAD

**Issue by snv** [ExpediaGroup/graphql-kotlin#1020]
**Library Version**
4.0.0-alpha11

**Describe the bug**
Trying to use the ktor-client with a ktor version larger than 1.3.1 leads to

```
HelloWorld examples
Exception in thread "main" java.lang.NoSuchMethodError: io.ktor.http.URLUtilsJvmKt.takeFrom(Lio/ktor/http/URLBuilder;Ljava/net/URL;)V
	at com.expediagroup.graphql.client.GraphQLKtorClient.execute$suspendImpl(GraphQLKtorClient.kt:129)
	at com.expediagroup.graphql.client.GraphQLKtorClient.execute(GraphQLKtorClient.kt)
	at com.expediagroup.graphql.generated.HelloWorldQuery.execute(HelloWorldQuery.kt:31)
	at com.expediagroup.graphql.generated.HelloWorldQuery.execute$default(HelloWorldQuery.kt:16)
	at com.expediagroup.graphql.examples.client.ApplicationKt$main$1.invokeSuspend(Application.kt:41)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.expediagroup.graphql.examples.client.ApplicationKt.main(Application.kt:40)
	at com.expediagroup.graphql.examples.client.ApplicationKt.main(Application.kt)
```

**To Reproduce**

1. Run the graphql-kotlin/examples/client/gradle-client/ as provided in commit fad9728 according to readme. -> Works as expected.
2. Change `build.gradle.kts` to use more current versions of kotlin and ktor
```
diff --git a/examples/client/gradle-client/build.gradle.kts b/examples/client/gradle-client/build.gradle.kts
--- a/examples/client/gradle-client/build.gradle.kts	(revision 8889faf4874ca08197f7ee65850db63a0adeff2a)
+++ b/examples/client/gradle-client/build.gradle.kts	(date 1610967486545)
@@ -4,7 +4,7 @@
 
 plugins {
     application
-    id("org.jetbrains.kotlin.jvm") version "1.3.72"
+    id("org.jetbrains.kotlin.jvm") version "1.4.21"
     id("com.expediagroup.graphql") version "4.0.0-alpha.1"
 }
 
@@ -15,8 +15,8 @@
 
 dependencies {
     implementation("com.expediagroup:graphql-kotlin-ktor-client:4.0.0-alpha.1")
-    implementation("io.ktor:ktor-client-okhttp:1.3.1")
-    implementation("io.ktor:ktor-client-logging-jvm:1.3.1")
+    implementation("io.ktor:ktor-client-okhttp:1.4.0")
+    implementation("io.ktor:ktor-client-logging-jvm:1.4.0")
 }
 
 application {
```
3. run `gradle clean build`
4. run `Application.kt`

**Expected behavior**
Same behavior as without changing the versions

**Comment by dariuszkuc** [comment]
Hello 👋 
AFAIK newer version of Ktor started releasing multiplatform artifacts which I guess is probably causing issues. `NoSuchMethodError` generally implies some classpath issue - you could try inspecting the project classpath to see the dependencies and provide overrides for those but it might not work. We recently also fixed Gradle plugin to separate its classpath from the buildscript classpath which should also some of the issue.

That being said I opened https://github.com/ExpediaGroup/graphql-kotlin/pull/1007 to bump up dependencies but I am hitting some weird build issue.

**Comment by snv** [comment]
Thanks, looking forward to the next release :)
