### ISSUE TITLE
Unable to find method ''void kotlin.jvm.internal.MutablePropertyReference1Impl when using gradle

### ISSUE THREAD

**Issue by pavel-luhin** [ExpediaGroup/graphql-kotlin#1080]
**Library Version**
4.0.0-alpha.15
Gradle version: 6.8
Kotlin version: 1.3.72

**Describe the bug**
When I try to do any graphql action (introspect schema, generate client) I got an exception 
```
Exception in thread "ktor-cio-dispatcher-worker-3" java.lang.NoClassDefFoundError: kotlinx/coroutines/CoroutinesInternalError
	at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.ClassNotFoundException: kotlinx.coroutines.CoroutinesInternalError
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 6 more
```

**To Reproduce**
Steps to reproduce the behavior. Please provide:
- Schema Configuration
- Kotlin code used to generate the schema

I apply plugin `id "com.expediagroup.graphql" version "4.0.0-alpha.15"` 
use dependency `implementation "com.expediagroup:graphql-kotlin-spring-client:4.0.0-alpha.15"`
and try to generate schema with this configuration
```
graphql {
    client {
        endpoint = "http://localhost:3003/graphql"
        packageName = "com.example.graphql.user"
    }
}
```
But got exception

**Comment by pavel-luhin** [comment]
Seems that issue gone invalidating caches
