### ISSUE TITLE
Examples build failing with exception

### ISSUE THREAD

**Issue by smyrick** [ExpediaGroup/graphql-kotlin#1084]
**Library Version**
Latest master branch

**Describe the bug**
The build is failing to compile the library on the task `client-examples:startWireMock`.

Running the gradle task from the command line doesn't trigger a failure. An exception is logged but the build is still marked as successful. Running from the IDE fails and stops the build.

```
Exception in thread "ktor-cio-dispatcher-worker-2" java.lang.NoClassDefFoundError: kotlinx/coroutines/CoroutinesInternalError
        at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.ClassNotFoundException: kotlinx.coroutines.CoroutinesInternalError
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 6 more
```

**To Reproduce**
```
cd examples
gw clean assemble
```

**Expected behavior**
There is no exception logged.

**Comment by dariuszkuc** [comment]
While I did encounter those exceptions occasionally they were not resulting in a build failure.

**Comment by smyrick** [comment]
Correct, they don't result in a failure if run from the command line, but do if run from my IDE

**Comment by huehnerlady** [comment]
I have the same issue. I found out that I can reproduce them by doing a 'clean' beforehand.

While this does not result in a build failure for me either, I do feel this should be looked at
