### ISSUE TITLE
IllegalArgumentException: object is not an instance of declaring class with Mono

### ISSUE THREAD

**Issue by eduan-envel** [ExpediaGroup/graphql-kotlin#1144]
**Library Version**
4.1.1 with Spring Boot 2.4.5

**Describe the bug**
Given a simple schema definition like this:
```
@Component
class UserApi : Query {
    fun user() = Mono.just(User("Bob", 21))
}

data class User(val name: String, val age: Int)
```
And this query:
```
query User {
  user {
    age
    name
  }
}
```
I get this exception:
```
java.lang.IllegalArgumentException: object is not an instance of declaring class
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97) ~[kotlin-reflect-1.4.32.jar:1.4.32-release-371 (1.4.32)]
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113) ~[kotlin-reflect-1.4.32.jar:1.4.32-release-371 (1.4.32)]
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108) ~[kotlin-reflect-1.4.32.jar:1.4.32-release-371 (1.4.32)]
	at com.expediagroup.graphql.generator.execution.PropertyDataFetcher.get(PropertyDataFetcher.kt:34) ~[graphql-kotlin-schema-generator-4.1.1.jar:4.1.1]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:270) ~[graphql-java-16.2.jar:na]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:203) ~[graphql-java-16.2.jar:na]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:60) ~[graphql-java-16.2.jar:na]
	at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:646) ~[graphql-java-16.2.jar:na]
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:438) ~[graphql-java-16.2.jar:na]
	at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:390) ~[graphql-java-16.2.jar:na]
	at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$1(ExecutionStrategy.java:205) ~[graphql-java-16.2.jar:na]
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2158) ~[na:na]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:204) ~[graphql-java-16.2.jar:na]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:60) ~[graphql-java-16.2.jar:na]
	at graphql.execution.Execution.executeOperation(Execution.java:165) ~[graphql-java-16.2.jar:na]
	at graphql.execution.Execution.execute(Execution.java:104) ~[graphql-java-16.2.jar:na]
	at graphql.GraphQL.execute(GraphQL.java:557) ~[graphql-java-16.2.jar:na]
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:482) ~[graphql-java-16.2.jar:na]
	at graphql.GraphQL.executeAsync(GraphQL.java:446) ~[graphql-java-16.2.jar:na]
	at com.expediagroup.graphql.server.execution.GraphQLRequestHandler.executeRequest$suspendImpl(GraphQLRequestHandler.kt:45) ~[graphql-kotlin-server-4.1.1.jar:4.1.1]
	at com.expediagroup.graphql.server.execution.GraphQLRequestHandler.executeRequest(GraphQLRequestHandler.kt) ~[graphql-kotlin-server-4.1.1.jar:4.1.1]
	at com.expediagroup.graphql.server.execution.GraphQLServer.execute$suspendImpl(GraphQLServer.kt:48) ~[graphql-kotlin-server-4.1.1.jar:4.1.1]
	at com.expediagroup.graphql.server.execution.GraphQLServer$execute$1.invokeSuspend(GraphQLServer.kt) ~[graphql-kotlin-server-4.1.1.jar:4.1.1]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.4.32.jar:1.4.32-release-371 (1.4.32)]
```
I believe it has something to do with the Mono because if you remove it like this then it works `fun user() = User("Bob", 21)`.
My actual use case is much more complex than this. This is my first time using this library so might just be something stupid I'm doing. Thanks in advance!

**Comment by dariuszkuc** [comment]
Hello 👋 
Have you followed the this setup -> https://expediagroup.github.io/graphql-kotlin/docs/schema-generator/execution/async-models#rxjavareactor?

**Comment by smyrick** [comment]
As mentioned, by default we don't know how to unwrap monos to the class you want to use for the schema. See the docs linked above on how to configure your hooks to support Mono
