### ISSUE TITLE
InvalidWrappedTypeException for kotlin.ByteArray

### ISSUE THREAD

**Issue by stasbit** [ExpediaGroup/graphql-kotlin#1334]
**Library Version**
```
<dependency>
        <groupId>com.expediagroup</groupId>
        <artifactId>graphql-kotlin-spring-server</artifactId>
        <version>5.2.0</version>
</dependency>

<dependency>
        <groupId>com.expediagroup</groupId>
        <artifactId>graphql-kotlin-schema-generator</artifactId>
        <version>5.2.0</version>
</dependency>
```

**Describe the bug**
During the service start there is an exception
```
Caused by: com.expediagroup.graphql.generator.exceptions.InvalidWrappedTypeException: Could not get the type of the first argument for the type kotlin.ByteArray
	at com.expediagroup.graphql.generator.internal.extensions.KTypeExtensionsKt.getTypeOfFirstArgument(kTypeExtensions.kt:60)
	at com.expediagroup.graphql.generator.internal.extensions.KTypeExtensionsKt.getWrappedType(kTypeExtensions.kt:66)
	at com.expediagroup.graphql.generator.internal.types.GenerateListKt.generateList(generateList.kt:25)
	at com.expediagroup.graphql.generator.internal.types.GenerateGraphQLTypeKt.getGraphQLType(generateGraphQLType.kt:69)
	at com.expediagroup.graphql.generator.internal.types.GenerateGraphQLTypeKt.access$getGraphQLType(generateGraphQLType.kt:1)
	at com.expediagroup.graphql.generator.internal.types.GenerateGraphQLTypeKt$objectFromReflection$1.invoke(generateGraphQLType.kt:62)
	at com.expediagroup.graphql.generator.internal.types.GenerateGraphQLTypeKt$objectFromReflection$1.invoke(generateGraphQLType.kt:61)
	at com.expediagroup.graphql.generator.internal.state.TypesCache.buildIfNotUnderConstruction$graphql_kotlin_schema_generator(TypesCache.kt:133)
	at com.expediagroup.graphql.generator.internal.types.GenerateGraphQLTypeKt.objectFromReflection(generateGraphQLType.kt:61)
	at com.expediagroup.graphql.generator.internal.types.GenerateGraphQLTypeKt.generateGraphQLType(generateGraphQLType.kt:40)
	at com.expediagroup.graphql.generator.internal.types.GenerateGraphQLTypeKt.generateGraphQLType$default(generateGraphQLType.kt:36)
	at com.expediagroup.graphql.generator.internal.types.GenerateFunctionKt.generateFunction(generateFunction.kt:54)
	at com.expediagroup.graphql.generator.internal.types.GenerateFunctionKt.generateFunction$default(generateFunction.kt:33)
	at com.expediagroup.graphql.generator.internal.types.GenerateQueryKt.generateQueries(generateQuery.kt:43)
	at com.expediagroup.graphql.generator.SchemaGenerator.generateSchema(SchemaGenerator.kt:80)
	at com.expediagroup.graphql.generator.SchemaGenerator.generateSchema$default(SchemaGenerator.kt:68)
	at com.expediagroup.graphql.generator.ToSchemaKt.toSchema(toSchema.kt:41)
	at com.expediagroup.graphql.server.spring.NonFederatedSchemaAutoConfiguration.schema(NonFederatedSchemaAutoConfiguration.kt:76)
	at com.expediagroup.graphql.server.spring.NonFederatedSchemaAutoConfiguration$$EnhancerBySpringCGLIB$$3e607c19.CGLIB$schema$1(<generated>)
	at com.expediagroup.graphql.server.spring.NonFederatedSchemaAutoConfiguration$$EnhancerBySpringCGLIB$$3e607c19$$FastClassBySpringCGLIB$$a199793b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.expediagroup.graphql.server.spring.NonFederatedSchemaAutoConfiguration$$EnhancerBySpringCGLIB$$3e607c19.schema(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
```

**To Reproduce**
Steps to reproduce the behavior. Please provide:
- schema generartion using generator from compenent graphql-kotlin-schema-generator
- used component graphql-kotlin-schema-generator

**Expected behavior**
Spring boot application started, graphQL schema generated.

**Comment by dariuszkuc** [comment]
Hello 👋 
Please provide your schema/code that causes the issue. Based on the exception it sounds like you are trying to use `ByteArray` which is not a valid GraphQL type. If you do need to use `ByteArray` then you will need to provide custom schema generator hook to correctly handle it (e.g. map it to a custom scalar).

**Comment by stasbit** [comment]
@dariuszkuc Thanks for a prompt response. I think that schema generation is done by component *graphql-kotlin-schema-generator* internally. But from the other hand I can see some custom SchemaGeneratorHooks in the Spring config of my app... So then I just need to add one more hook for `ByteArray`. Do we always need custom hooks for kotlin.* types?

**Comment by smyrick** [comment]
@stasbit This is the list of supported scalars out of the box: https://opensource.expediagroup.com/graphql-kotlin/docs/schema-generator/writing-schemas/scalars

This is the supported lists: https://opensource.expediagroup.com/graphql-kotlin/docs/schema-generator/writing-schemas/lists

Then every thing else must be a scalar, a list, or an object that is available through reflection: https://opensource.expediagroup.com/graphql-kotlin/docs/schema-generator/customizing-schemas/generator-config#schemageneratorconfig

**Comment by stasbit** [comment]
@smyrick Thanks a lot, sorry for reporting Question as a Bug. But anyway thanks for great support. I think we can resolve this issue.
