### ISSUE TITLE
Support value classes

### ISSUE THREAD

**Issue by rocketraman** [ExpediaGroup/graphql-kotlin#1370]
**Is your feature request related to a problem? Please describe.**
I often use value classes in my data models. However, while the schema generation appears to work correctly, at runtime graphql-kotlin fails when attempting to fetch the value class property. When serializing a class that uses them:

```
java.lang.IllegalArgumentException: argument type mismatch
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at kotlin.reflect.jvm.internal.calls.InlineClassAwareCaller.call(InlineClassAwareCaller.kt:145) ~[kotlin-reflect-1.6.10.jar:1.6.10-release-923(1.6.10)]
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108) ~[kotlin-reflect-1.6.10.jar:1.6.10-release-923(1.6.10)]
	at com.expediagroup.graphql.generator.execution.PropertyDataFetcher.get(PropertyDataFetcher.kt:34) ~[graphql-kotlin-schema-generator-5.3.2.jar:5.3.2]
	...
```

An explicit `GraphQLScalarType` with a `Coercing` implementation does not help.

**Describe the solution you'd like**
Value classes should not cause any issues.

**Comment by dariuszkuc** [comment]
Hello 👋,
Guessing this is due to the https://github.com/FasterXML/jackson-module-kotlin/issues/199. I believe with the proposed refactor of how we parse the input arguments (https://github.com/ExpediaGroup/graphql-kotlin/pull/1379) we should be able to support it.

**Comment by dariuszkuc** [comment]
#1379 added support for handling ID value class only, looks like we may need to make some additional changes to correctly handle it
