### ISSUE TITLE
Spurious type name conflict with Input type wrapping different type without the `Input` suffix

### ISSUE THREAD

**Issue by rocketraman** [ExpediaGroup/graphql-kotlin#1410]
**Library Version**
6.0.0-alpha.0

**Describe the bug**
I have a mutation that looks like this:

```
data class NotificationSettingsInput(
  val settings: NotificationSettings,
)

sealed interface NotificationSettingsPayload

suspend fun updateNotificationSettings(input: NotificationSettingsInput): NotificationSettingsPayload
```

This results in the following spurious error at schema generation time:

```
graphql.AssertException: All types within a GraphQL schema must have unique names. No two provided types may have the same name.
No provided type may have a name which conflicts with any built in types (including Scalar and Introspection types).
You have redefined the type 'NotificationSettingsInput' from being a 'GraphQLInputObjectType' to a 'GraphQLInputObjectType'
	at graphql.schema.impl.GraphQLTypeCollectingVisitor.assertTypeUniqueness(GraphQLTypeCollectingVisitor.java:118) ~[graphql-java-17.2.jar:?]
	at graphql.schema.impl.GraphQLTypeCollectingVisitor.visitGraphQLInputObjectType(GraphQLTypeCollectingVisitor.java:62) ~[graphql-java-17.2.jar:?]
	at graphql.schema.impl.MultiReadOnlyGraphQLTypeVisitor.lambda$visitGraphQLInputObjectType$7(MultiReadOnlyGraphQLTypeVisitor.java:92) ~[graphql-java-17.2.jar:?]
	at java.util.Arrays$ArrayList.forEach(Arrays.java:4204) ~[?:?]
	at graphql.schema.impl.MultiReadOnlyGraphQLTypeVisitor.visitGraphQLInputObjectType(MultiReadOnlyGraphQLTypeVisitor.java:92) ~[graphql-java-17.2.jar:?]
	at graphql.schema.GraphQLInputObjectType.accept(GraphQLInputObjectType.java:142) ~[graphql-java-17.2.jar:?]
	at graphql.schema.SchemaTraverser$TraverserDelegateVisitor.enter(SchemaTraverser.java:87) ~[graphql-java-17.2.jar:?]
	at graphql.util.Traverser.traverse(Traverser.java:144) ~[graphql-java-17.2.jar:?]
	at graphql.schema.SchemaTraverser.doTraverse(SchemaTraverser.java:74) ~[graphql-java-17.2.jar:?]
	at graphql.schema.SchemaTraverser.depthFirst(SchemaTraverser.java:64) ~[graphql-java-17.2.jar:?]
	at graphql.schema.SchemaTraverser.depthFirst(SchemaTraverser.java:57) ~[graphql-java-17.2.jar:?]
	at graphql.schema.impl.SchemaUtil.visitPartiallySchema(SchemaUtil.java:61) ~[graphql-java-17.2.jar:?]
	at graphql.schema.GraphQLSchema$Builder.buildImpl(GraphQLSchema.java:810) ~[graphql-java-17.2.jar:?]
	at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:787) ~[graphql-java-17.2.jar:?]
	at com.expediagroup.graphql.generator.SchemaGenerator.generateSchema(SchemaGenerator.kt:93) ~[graphql-kotlin-schema-generator-6.0.0-alpha.0.jar:6.0.0-alpha.0]
	at com.expediagroup.graphql.generator.SchemaGenerator.generateSchema$default(SchemaGenerator.kt:69) ~[graphql-kotlin-schema-generator-6.0.0-alpha.0.jar:6.0.0-alpha.0]
	at com.expediagroup.graphql.generator.ToSchemaKt.toSchema(toSchema.kt:41) ~[graphql-kotlin-schema-generator-6.0.0-alpha.0.jar:6.0.0-alpha.0]
	at com.expediagroup.graphql.generator.ToSchemaKt.toSchema$default(toSchema.kt:33) ~[graphql-kotlin-schema-generator-6.0.0-alpha.0.jar:6.0.0-alpha.0]
```

Note that if the "inner" class is renamed from `NotificationSettings` to `NotificationSettings1` then everything works fine (and there is no `NotificationSettings1Input` in the resulting schema, which proves that `NotificationSettings` is not being used elsewhere as an input type).

However, if an `@GraphQLName("NotificationSettings1Input")` annotation is added to the `NotificationSettingInput` class, then the output schema looks incorrectly like this:

```
input NotificationSettings1Input {
  settings: NotificationSettingsInput!
}

input NotificationSettingsInput {
  ...
}
```

**Expected behavior**
I wouldn't expect any error in this case -- the input type and the contained type are clearly different so the schema generator shouldn't be trying to add the "Input" suffix to any type.

**Comment by rocketraman** [comment]
Ah, I think I misunderstood something... the "Input" suffix is added even if that type isn't at the top-level of the input hierarchy, except if the value is a scalar or enum.
