### ISSUE TITLE
GraphQLClientGenerator fails when KotlinPoet upgraded to latest stable version

### ISSUE THREAD

**Issue by bsorbo** [ExpediaGroup/graphql-kotlin#1426]
**Library Version**
At least from 5.2.0 on up.

**Describe the bug**
GraphQLClientGenerator, when using kotlin-poet to define data class constructor parameters, specifies `KModifier.OVERRIDE` on the addParameter call. In kotlin-poet v1.11.0, behavior was recently changed to disallow this, which causes the following error message when using that version:
```
Exception in thread "main" java.lang.IllegalArgumentException: Modifiers [OVERRIDE] are not allowed on Kotlin parameters. Allowed modifiers: [VARARG, NOINLINE, CROSSINLINE]
        at com.squareup.kotlinpoet.ParameterSpec.<init>(ParameterSpec.kt:41)
        at com.squareup.kotlinpoet.ParameterSpec.<init>(ParameterSpec.kt:29)
        at com.squareup.kotlinpoet.ParameterSpec$Builder.build(ParameterSpec.kt:157)
        at com.squareup.kotlinpoet.FunSpec$Builder.addParameter(FunSpec.kt:465)
        at com.expediagroup.graphql.plugin.client.generator.GraphQLClientGenerator.generate$graphql_kotlin_client_generator(GraphQLClientGenerator.kt:162)
        at com.expediagroup.graphql.plugin.client.generator.GraphQLClientGenerator.generate(GraphQLClientGenerator.kt:68)
        at com.expediagroup.graphql.plugin.client.GenerateClientKt.generateClient(generateClient.kt:47)
        at com.expediagroup.graphql.plugin.client.GenerateClientKt.generateClient$default(generateClient.kt:29)
        ...
```

This change in behavior in KotlinPoet is listed as a bug-fix in [the 1.11.0 release notes](https://github.com/square/kotlinpoet/releases/tag/1.11.0), and the maintainer confirmed this is the expected behavior from KotlinPoet in [this now-closed Github Issue](https://github.com/square/kotlinpoet/issues/1230), while also pointing out the fix.

**To Reproduce**
Change the `kotlinPoetVersion` in `gradle.properties` to `1.11.0`, then run `./gradlew check`. Various existing tests fail.

**Expected behavior**
I would expect tests to pass/schema generation to succeed when using the latest stable version of kotlin-poet.

**Comment by bsorbo** [comment]
Hope it's ok to ask a question here, I was looking at submitting a PR for this myself, but another issue with upgrading KotlinPoet to `1.11.0` is that most of the `verifyClientGeneration`-based tests fail, since in that version KotlinPoet [also started adding trailing commas to multi-line parameters](https://github.com/square/kotlinpoet/releases/tag/1.11.0).

The diff is thus pretty extensive - is there a gradle task to re-baseline the expected test results? I couldn't find anything, but was hoping I just missed that since we could easily validate the re-baseline (check that it just added commas), otherwise going through files one-by-one would be fairly tedious.

**Comment by dariuszkuc** [comment]
Hello 👋 
PRs are always welcome!

Indeed the trailing comma part was the reason why I did not update `kotlinpoet` together with other dependencies recently. Sadly there is no automated way to re-base it so ATM it is a manual process 😞.

**Comment by bsorbo** [comment]
Ok, thanks for confirming. I don't know if I'll get to this immediately but seems like a good intro PR.
