### ISSUE TITLE
KotlinReflectionInternalError when mapping mutation input to inline value classes

### ISSUE THREAD

**Issue by EXPEylazzari** [ExpediaGroup/graphql-kotlin#1564]
**Library Version**
GraphQL Kotlin version: 6.2.0
Kotlin version: 1.6.21

**Describe the bug**
When defining mutations that have fields that are objects that in turn contain fields that map to an inline value class (e.g. a scalar type such as `ID`), the following exception is thrown:

```
kotlin.reflect.jvm.internal.KotlinReflectionInternalError: This callable does not support a default call: ...
Original Stack Trace:
		at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:164) ~[kotlin-reflect-1.6.21.jar:1.6.21-release-334(1.6.21)]
		at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:112) ~[kotlin-reflect-1.6.21.jar:1.6.21-release-334(1.6.21)]
		at com.expediagroup.graphql.generator.execution.ConvertArgumentValueKt.mapToKotlinObject(convertArgumentValue.kt:121) ~[graphql-kotlin-schema-generator-6.2.2.jar:6.2.2]
		at com.expediagroup.graphql.generator.execution.ConvertArgumentValueKt.convertValue(convertArgumentValue.kt:76) ~[graphql-kotlin-schema-generator-6.2.2.jar:6.2.2]
		at com.expediagroup.graphql.generator.execution.ConvertArgumentValueKt.convertArgumentValue(convertArgumentValue.kt:54) ~[graphql-kotlin-schema-generator-6.2.2.jar:6.2.2]
		at com.expediagroup.graphql.generator.execution.FunctionDataFetcher.mapParameterToValue(FunctionDataFetcher.kt:101) ~[graphql-kotlin-schema-generator-6.2.2.jar:6.2.2]
		at com.expediagroup.graphql.server.spring.execution.SpringDataFetcher.mapParameterToValue(SpringDataFetcher.kt:48) ~[graphql-kotlin-spring-server-6.2.2.jar:6.2.2]
		at com.expediagroup.graphql.generator.execution.FunctionDataFetcher.getParameters(FunctionDataFetcher.kt:79) ~[graphql-kotlin-schema-generator-6.2.2.jar:6.2.2]
		at com.expediagroup.graphql.generator.execution.FunctionDataFetcher.get(FunctionDataFetcher.kt:58) ~[graphql-kotlin-schema-generator-6.2.2.jar:6.2.2]
		at graphql.execution.instrumentation.dataloader.DataLoaderDispatcherInstrumentation.lambda$instrumentDataFetcher$0(DataLoaderDispatcherInstrumentation.java:86) ~[graphql-java-19.1.jar:?]
```

For full context, see this [Slack thread](https://kotlinlang.slack.com/archives/CQLNT7B29/p1664394926167649).

**Note**: this does **not** seem to happen when the inline value class field is declared as a top-level field in the mutation.

**To Reproduce**

Let's say you have this simple input type:

```kotlin
data class UserInput(id: ID, firstName: String? = null, lastName: String? = null)
```

and mutation:

``` kotlin
fun updateUser(user: UserInput): Boolean = true
```

giving us schema:

```graphql
type Mutation {
  updateUser(user: User!): Boolean!
}

input UserInput {
  id: ID!
  firstName: String
  lastName: String
}
```

So, a mutation where you can either update a user's first name, or last name, or both, or nothing.

If you call it with all fields specified, it works:

```graphql
mutation {
  updateUser(
    user: {
      id: "123"
      firstName: "John"
      lastName: "Doe"
    }
  )
} 
```

but if you just specify either only the first name (or last name):

```graphql
mutation {
  updateUser(
    user: {
      id: "123"
      firstName: "John"
    }
  )
}  
```

it fails with the exception mentioned above.

**Expected behavior**

There is nothing wrong in wanting to declare a mutation that has this shape backed by a data class that has this definition, so I would expect this to work.

**Known fixes**

As suggested in the Slack thread where this issue was first discussed, bumping the Kotlin version to 1.7.x seems to fix the issue without having to do anything else. 

This is actually a known issue called out in one of the test cases ([here](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/execution/ConvertArgumentValueTest.kt#L177)), and the underlying root cause is Kotlin lang issue [KT-27598](https://youtrack.jetbrains.com/issue/KT-27598), which is fixed in Kotlin 1.7.x.

**Comment by samuelAndalon** [comment]
We have added updating to kotlin 1.7.x to the 7.x.x milestone
https://github.com/ExpediaGroup/graphql-kotlin/issues/1549

https://github.com/ExpediaGroup/graphql-kotlin/milestone/5

**Comment by samuelAndalon** [comment]
https://github.com/ExpediaGroup/graphql-kotlin/pull/1572
