### ISSUE TITLE
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "isCustomerEligible" 

### ISSUE THREAD

**Issue by viralpatel-phx** [ExpediaGroup/graphql-kotlin#1569]
**Library Version**
GraphQL Kotlin version: 6.2.5
Kotlin version: 1.7.0
Spring Boot: 2.7.0

**Describe the bug**
Getting `com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException` exception when serialising the JSON data `{"data":{"isCustomerEligible":{"eligibility":false}}}` from response. The issue only occurs for the below query. 

Complete exception:
```

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "isCustomerEligible" (class com.example.graphql.client.iscustomereligible.CustomerEligibilityResponse), not marked as ignorable (one known property: "eligibility"])
 at [Source: (String)"{"data":{"isCustomerEligible":{"eligibility":false}}}
"; line: 1, column: 50] (through reference chain: com.expediagroup.graphql.client.jackson.types.JacksonGraphQLResponse["data"]->com.example.graphql.client.iscustomereligible.CustomerEligibilityResponse["isCustomerEligible"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2023)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1650)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:539)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:219)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:186)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1398)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:563)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:438)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
        at com.expediagroup.graphql.client.jackson.GraphQLClientJacksonSerializer.deserialize(GraphQLClientJacksonSerializer.kt:49)
        at com.expediagroup.graphql.client.jackson.GraphQLClientJacksonSerializer.deserialize(GraphQLClientJacksonSerializer.kt:35)
        at com.expediagroup.graphql.client.spring.GraphQLWebClient.execute$suspendImpl(GraphQLWebClient.kt:48)
        at com.expediagroup.graphql.client.spring.GraphQLWebClient$execute$1.invokeSuspend(GraphQLWebClient.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at com.example.stepdefinition.ExampleService.getCustomerEligibility(ExampleService.kt:84)
  
```

**To Reproduce**
Steps to reproduce the behavior. Please provide:
- Schema Configuration
schema:
```graphql
type Query {
   ...
   isCustomerEligible: CustomerEligibilityResponse
   ...
}

type CustomerEligibilityResponse {
  eligibility: Boolean
}
```

- Kotlin code used to generate the schema

GraphQL Query: 
isCustomerEligible.graphql
```graphql
query IsCustomerEligible {
    isCustomerEligible {
        eligibility
    }
}
```

Generated code:
CustomerElibilityResponse.kt

```kotlin
package com.example.graphql.client.iscustomereligible

import com.expediagroup.graphql.client.Generated
import kotlin.Boolean

@Generated
public data class CustomerEligibilityResponse(
  public val eligibility: Boolean? = null,
)
```

IsCustomerEligible.kt
```kotlin
package com.example.graphql.client

import com.expediagroup.graphql.client.Generated
import com.expediagroup.graphql.client.types.GraphQLClientRequest
import kotlin.String
import kotlin.reflect.KClass
import com.example.graphql.client.iscustomereligible.CustomerEligibilityResponse

public const val IS_CUSTOMER_ELIGIBLE: String =
    "query IsCustomerEligible {\n    isCustomerEligible {\n        eligibility\n    }\n}"

@Generated
public class IsCustomerEligible : GraphQLClientRequest<IsCustomerEligible.Result> {
  public override val query: String = IS_CUSTOMER_ELIGIBLE

  public override val operationName: String = "IsCustomerEligible"

  public override fun responseType(): KClass<IsCustomerEligible.Result> = IsCustomerEligible.Result::class

  @Generated
  public data class Result(
    public val isCustomerEligible: CustomerEligibilityResponse? = null,
  )
}
```

Business function calling GraphQL client:
```kotlin
fun getCustomerEligibility(): IsCustomerEligible.Result {
        return runBlocking {
            graphQLService.execute(IsCustomerEligible()).data!!
        }
    }
```

**Expected behavior**

No exception should be generated.

**Comment by viralpatel-phx** [comment]
I was also able to reproduce the problem by invoking `GraphQLClientJacksonSerializer.deserialize` method directly.

```
import com.expediagroup.graphql.client.jackson.GraphQLClientJacksonSerializer

fun main() {
    val gql = "{\"data\":{\"isCustomerEligible\":{\"eligibility\":false}}}"
    val serializer = GraphQLClientJacksonSerializer()

    serializer.deserialize(gql, IsCustomerEligible.Result::class)
}
```

Output:
```
Exception in thread "main" com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "isCustomerEligible" (class com.example.graphql.client.iscustomereligible.CustomerEligibilityResponse), not marked as ignorable (one known property: "eligibility"])
 at [Source: (String)"{"data":{"isCustomerEligible":{"eligibility":false}}}"; line: 1, column: 50] (through reference chain: com.expediagroup.graphql.client.jackson.types.JacksonGraphQLResponse["data"]->com.example.graphql.client.iscustomereligible.CustomerEligibilityResponse["isCustomerEligible"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2023)
```

The `IsCustomerEligible.Result` is generated class attached in the issue description.
