### ISSUE TITLE
`java.lang.NoSuchMethodError` when connecting to subscriptions (Spring server)

### ISSUE THREAD

**Issue by SonMooSans** [ExpediaGroup/graphql-kotlin#1666]
**Library Version**
6.3.4

**Describe the bug**

The schema is generated correctly with `spring boot` 2.7.8 and `graphql-kotlin-spring-server` 6.3.4
When testing subscriptions in the playground or apollo client (subscriptions-transport-ws), an error is thrown
```
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'graphql.execution.instrumentation.ExecutionStrategyInstrumentationContext graphql.execution.instrumentation.Instrumentation.beginExecutionStrategy(graphql.execution.instrumentation.parameters.InstrumentationExecutionStrategyParameters, graphql.execution.instrumentation.InstrumentationState)'
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1194) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309) ~[na:na]
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:556) ~[graphql-java-18.3.jar:na]
	at graphql.GraphQL.executeAsync(GraphQL.java:524) ~[graphql-java-18.3.jar:na]
	at graphql.GraphQL.execute(GraphQL.java:450) ~[graphql-java-18.3.jar:na]
	at com.expediagroup.graphql.server.spring.subscriptions.SpringGraphQLSubscriptionHandler.executeSubscription(SpringGraphQLSubscriptionHandler.kt:49) ~[graphql-kotlin-spring-server-6.3.4.jar:6.3.4]
	at com.expediagroup.graphql.server.spring.subscriptions.ApolloSubscriptionProtocolHandler.startSubscription(ApolloSubscriptionProtocolHandler.kt:133) ~[graphql-kotlin-spring-server-6.3.4.jar:6.3.4]
	at com.expediagroup.graphql.server.spring.subscriptions.ApolloSubscriptionProtocolHandler.handle(ApolloSubscriptionProtocolHandler.kt:67) ~[graphql-kotlin-spring-server-6.3.4.jar:6.3.4]
	at com.expediagroup.graphql.server.spring.subscriptions.SubscriptionWebSocketHandler.handle$lambda-0(SubscriptionWebSocketHandler.kt:35) ~[graphql-kotlin-spring-server-6.3.4.jar:6.3.4]
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:386) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:113) ~[reactor-core-3.4.26.jar:3.4.26]
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:294) ~[reactor-netty-core-1.0.27.jar:1.0.27]
	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:403) ~[reactor-netty-core-1.0.27.jar:1.0.27]
	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:404) ~[reactor-netty-core-1.0.27.jar:1.0.27]
	at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:627) ~[reactor-netty-http-1.0.27.jar:1.0.27]
	at reactor.netty.http.server.WebsocketServerOperations.onInboundNext(WebsocketServerOperations.java:171) ~[reactor-netty-http-1.0.27.jar:1.0.27]
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113) ~[reactor-netty-core-1.0.27.jar:1.0.27]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.lang.NoSuchMethodError: 'graphql.execution.instrumentation.ExecutionStrategyInstrumentationContext graphql.execution.instrumentation.Instrumentation.beginExecutionStrategy(graphql.execution.instrumentation.parameters.InstrumentationExecutionStrategyParameters, graphql.execution.instrumentation.InstrumentationState)'
	at com.expediagroup.graphql.generator.execution.FlowSubscriptionExecutionStrategy.execute(FlowSubscriptionExecutionStrategy.kt:61) ~[graphql-kotlin-schema-generator-6.3.4.jar:6.3.4]
	at graphql.execution.Execution.executeOperation(Execution.java:159) ~[graphql-java-18.3.jar:na]
	at graphql.execution.Execution.execute(Execution.java:105) ~[graphql-java-18.3.jar:na]
	at graphql.GraphQL.execute(GraphQL.java:641) ~[graphql-java-18.3.jar:na]
	at graphql.GraphQL.lambda$parseValidateAndExecute$11(GraphQL.java:561) ~[graphql-java-18.3.jar:na]
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187) ~[na:na]
	... 44 common frames omitted
```

After that, the connection has failed

**To Reproduce**

Create a new spring reactive project and setup graphql-kotlin correctly

Create `CountSubscription` class:
```kotlin
package net.sonmoosans.sharkchat.subscription;

import com.expediagroup.graphql.generator.annotations.GraphQLDescription
import com.expediagroup.graphql.server.operations.Subscription
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.reactive.asPublisher
import org.reactivestreams.Publisher
import org.slf4j.Logger
import org.slf4j.LoggerFactory
import org.springframework.stereotype.Component
import reactor.core.publisher.Flux
import java.time.Duration
import kotlin.random.Random

@Component
class CounterSubscription : Subscription {

    val logger: Logger = LoggerFactory.getLogger(CounterSubscription::class.java)

    @GraphQLDescription("Returns a single value")
    fun singleValueSubscription(): Flux<Int> = Flux.just(1)

    @GraphQLDescription("Returns a random number every second")
    fun counter(): Flux<Int> = Flux.interval(Duration.ofSeconds(1)).map {
        val value = Random.nextInt()
        logger.info("Returning $value from counter")
        value
    }

    @GraphQLDescription("Returns a random number every second, errors if even")
    fun counterWithError(): Flux<Int> = Flux.interval(Duration.ofSeconds(1))
        .map {
            val value = Random.nextInt()
            if (value % 2 == 0) {
                throw Exception("Value is even $value")
            } else value
        }

    @GraphQLDescription("Returns one value then an error")
    fun singleValueThenError(): Flux<Int> = Flux.just(1, 2)
        .map { if (it == 2) throw Exception("Second value") else it }

    @GraphQLDescription("Returns stream of values")
    fun flow(): Publisher<Int> = flowOf(1, 2, 4).asPublisher()
}
```
Start the application

**Expected behavior**
It should be connected with no problem

I fixed it by adding `implementation("com.graphql-java:graphql-java:20.0")` directly into dependencies
However, I think it should be counted as a bug

**Comment by dariuszkuc** [comment]
Hello 👋 
`java.lang.NoSuchMethodError` implies classpath issue. By introducing Spring GraphQL module, SpringBoot now defines also `graphql-java` dependency.

- `graphql-kotlin v6.3.4` relies on `graphql-java v19.2` ([link]( https://github.com/ExpediaGroup/graphql-kotlin/blob/6.3.4/gradle.properties#L26))
- `SpringBoot v2.7.8` specifies a dependency on `graphql-java v18.3` ([link](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.7.8/spring-boot-dependencies-2.7.8.pom))

If you are using SpringBoot plugin for managing dependencies (i.e apply `io.spring.dependency-management`) then it will attempt to pull in old version of GraphQL Java which will blow up due to backwards incompatible change introduced in v19. Proper fix is to override the SpringBoot dependency -> you can either specify the dependency directly (as you mentioned above) or by specifying the `graphql-java.version=19.2` property in your `gradle.properties`.

NOTE: SpringBoot v3 bumps the `graphql-java` dependency to `19.2` whereas `v20.0` is already out
