### ISSUE TITLE
FLoats in Mutations

### ISSUE THREAD

**Issue by morphace** [ExpediaGroup/graphql-kotlin#1730]
**Library Version**
6.4.0

**Describe the bug**
We just now migrate to version 6.4.0. I tested our mutations and I found an issue to Float types (which we didn't have in version 5.x). Once I have a Float type in my signature (an object containing a float), then my backend throws an exception (see below). Using a kt.Double fixes the issue:

**To Reproduce**
Steps to reproduce the behavior. Please provide:
- Create a mutation that contains a float as a parameter
- Invoke that mutation

**Expected behavior**
No exception

Excpetion that I get:
`java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[na:na]
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Constructor.call(CallerImpl.kt:41) ~[kotlin-reflect-1.8.10.jar!/:1.8.10-release-430(1.8.10)]
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:173) ~[kotlin-reflect-1.8.10.jar!/:1.8.10-release-430(1.8.10)]
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:112) ~[kotlin-reflect-1.8.10.jar!/:1.8.10-release-430(1.8.10)]
	at com.expediagroup.graphql.generator.execution.ConvertArgumentValueKt.mapToKotlinObject(convertArgumentValue.kt:121) ~[graphql-kotlin-schema-generator-6.4.0.jar!/:6.4.0]
`

**Comment by samuelAndalon** [comment]
https://opensource.expediagroup.com/graphql-kotlin/docs/schema-generator/writing-schemas/scalars/#primitive-types
