### ISSUE TITLE
GetCurrentFutures ArrayIndexOutOfBoundsException issue

### ISSUE THREAD

**Issue by younseunghyun** [ExpediaGroup/graphql-kotlin#1837]
**Library Version**
6.3.4

**Describe the bug**
Sometime when batch query exexcuted following error are occurred

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 565 out of bounds for length 565
	at java.base/java.util.HashMap.valuesToArray(HashMap.java:973)
	at java.base/java.util.HashMap$Values.toArray(HashMap.java:1050)
	at java.base/java.util.ArrayList.addAll(ArrayList.java:670)
	at kotlin.collections.CollectionsKt__MutableCollectionsKt.addAll(MutableCollections.kt:116)
	at kotlin.collections.CollectionsKt__IterablesKt.flatten(Iterables.kt:49)
	at com.expediagroup.graphql.dataloader.KotlinDataLoaderRegistry.getCurrentFutures(KotlinDataLoaderRegistry.kt:64)
```

**To Reproduce**
Hard to reproduce.
Condition
1. Batch Query
2. Large amount of entries
 
**Expected behavior**
getCurrentFutures have to be thread safe.
may be avoid to use flatten

**Comment by samuelAndalon** [comment]
probably related to 
https://github.com/ExpediaGroup/graphql-kotlin/issues/1819

taking a look

**Comment by younseunghyun** [comment]
@samuelAndalon Yes it looks same.
Is there are any suggestion way to handle this issue?

Should I have to implement cacheMap with thread-safe hashmap?

**Comment by samuelAndalon** [comment]
gonna look into this today, it is a synchronization issue, will make it thread safe

**Comment by samuelAndalon** [comment]
https://github.com/ExpediaGroup/graphql-kotlin/releases/tag/6.5.5

**Comment by younseunghyun** [comment]
@samuelAndalon Thx 
I will test and let you know

**Comment by younseunghyun** [comment]
@samuelAndalon 
This patch reduce the error  frequency lower. 
But the same error is occured.
I make a PR #1843 for this issue.
