### ISSUE TITLE
Returning Flow in the Subscription results in InvalidSubscriptionTypeException if used with Federation

### ISSUE THREAD

**Issue by charlee-dev** [ExpediaGroup/graphql-kotlin#1862]
**Library Version**
What version are you using?
7.0.1

**Describe the bug**
Using the Ktor server example, taking a look at subscriptions which I want to use later in the chat and I noticed that every time I use Flow as a return type of the subscription, I get the `InvalidSubscriptionTypeException`, using Publisher works as expected, with no error. Error happens only if using FederatedSchemaGeneratorHooks.

**To Reproduce**
Steps to reproduce the behavior. Please provide:
```kotlin
// Plugin
install(GraphQL) {
    schema {
        packages = listOf(
            "${PACKAGE_NAME}.domain.model",
            "${PACKAGE_NAME}.feature",
        )
        queries = listOf(
            ...
        )
        mutations = listOf(
            ...
        )
        subscriptions = listOf(
            MessageSchema.Subscriptions(),
        )

        schemaObject = CustomSchema()

// Commenting out hooks and federation fixes the issue
        hooks = FederatedSchemaGeneratorHooks(emptyList(), optInFederationV2 = true)

        federation {
            enabled = true
            tracing {
                enabled = true
                debug = false
            }
        }
    }
    server {
        contextFactory = CustomGraphQLContextFactory()
        jacksonConfiguration = { }
        requestParser = KtorGraphQLRequestParser(jacksonObjectMapper().apply(jacksonConfiguration))
    }
}
```
Subscription:
```kotlin
class Subscriptions : Subscription {
 
// Results in InvalidSubscriptionTypeException
    @GraphQLDescription("Returns a random number every second, errors if even")
    fun counterWithError(): Flow<Int> = flow { 
        while (true) {
            val value = Random.nextInt()
            if (value % 2 == 0) {
                throw Exception("Value is even $value")
            } else emit(value)
            delay(1000)
        }
    }

// No error
    @GraphQLDescription("Returns stream of errors")
    fun flowOfErrors(): Publisher<DataFetcherResult<String?>> {
        val dfr: DataFetcherResult<String?> = DataFetcherResult.newResult<String?>()
            .data(null)
            .error(GraphqlErrorException.newErrorException().cause(Exception("error thrown")).build())
            .build()

        return flowOf(dfr, dfr).asPublisher()
    }
}
```
Error:
```kotlin
Exception in thread "main" com.expediagroup.graphql.generator.exceptions.InvalidSubscriptionTypeException: Schema requires all subscriptions to be public and return a valid type from the hooks. Subscriptions has PUBLIC visibility modifier. The function return type is Flow
	at com.expediagroup.graphql.generator.internal.types.GenerateSubscriptionKt.generateSubscriptions(generateSubscription.kt:50)
	at com.expediagroup.graphql.generator.SchemaGenerator.generateSchema(SchemaGenerator.kt:82)
	at com.expediagroup.graphql.generator.federation.FederatedSchemaGenerator.generateSchema(FederatedSchemaGenerator.kt:45)
	at com.expediagroup.graphql.generator.SchemaGenerator.generateSchema$default(SchemaGenerator.kt:58)
	at com.expediagroup.graphql.generator.federation.ToFederatedSchemaKt.toFederatedSchema(toFederatedSchema.kt:44)
	at com.expediagroup.graphql.server.ktor.GraphQL.<init>(GraphQL.kt:91)
	at com.expediagroup.graphql.server.ktor.GraphQL$Plugin.install(GraphQL.kt:183)
	at com.expediagroup.graphql.server.ktor.GraphQL$Plugin.install(GraphQL.kt:178)
	at io.ktor.server.application.ApplicationPluginKt.install(ApplicationPlugin.kt:100)
	at com.charleex.soulsync.plugins.GraphQlKt.configureGraphQL(GraphQl.kt:25)
	at com.charleex.soulsync.ApplicationKt.myApplicationModule(Application.kt:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:188)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:111)
	at io.ktor.server.engine.internal.CallableUtilsKt.callFunctionWithInjection(CallableUtils.kt:119)
	at io.ktor.server.engine.internal.CallableUtilsKt.executeModuleFunction(CallableUtils.kt:36)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$launchModuleByName$1.invoke(ApplicationEngineEnvironmentReloading.kt:332)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$launchModuleByName$1.invoke(ApplicationEngineEnvironmentReloading.kt:331)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartupFor(ApplicationEngineEnvironmentReloading.kt:356)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.launchModuleByName(ApplicationEngineEnvironmentReloading.kt:331)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.access$launchModuleByName(ApplicationEngineEnvironmentReloading.kt:32)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:319)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:310)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartup(ApplicationEngineEnvironmentReloading.kt:338)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:310)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:150)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:277)
	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:216)
	at com.charleex.soulsync.ApplicationKt.main(Application.kt:20)
	at com.charleex.soulsync.ApplicationKt.main(Application.kt)
```

**Expected behavior**
Expected working subscription, no error.

**Comment by dariuszkuc** [comment]
Hello 👋 
Good callout. In order to use `Flow` as a return type we need a custom hook to support it which is handled automatically for non federated schemas. Federated hooks did not support `Flow` as subscriptions were not supported by Federation up until recently (v2.4+). Looks like we forgot to update the hook.
