### ISSUE TITLE
Kotlin Ktor server io.ktor.serialization.JsonConvertException

### ISSUE THREAD

**Issue by charlee-dev** [ExpediaGroup/graphql-kotlin#1870]
**Library Version**
What version are you using?
expedia = "7.0.1"
ktor = "2.3.5"

**Describe the bug**
The query response has the wrong JSON structure. In my case response body instead of being `GraphQLResponse<AuthResponse>` is `GraphQLResponse<OperationName<AuthResponse>>`

Here is my model:
```kotlin
data class AuthResponse(
    val token: String,
    val userMinimal: UserMinimal,
)
```

And the mutation:
```kotlin
suspend fun login(
    authInput: AuthInput,
): AuthResponse {
     ...
}
```

And the query:
```kotlin
private const val QUERY =
    "mutation register(\$authInput: AuthInput!) { register(authInput: \$authInput) { token userMinimal { id email }}}"
```

Expected response:
```json
{
  "data" : {
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI2NTMwNzhjZWNlZWQ5NzJkZjMwMjM5MDMiLCJ1c2VySWQiOiI2NTMwNzhjZWNlZWQ5NzJkZjMwMjM5MDMifQ.68kjUteMAI-Vnz9r8xQlDTqEKFGh34VKy94PH5DXctY",
    "userMinimal" : {
      "id" : "653078ceceed972df3023903",
      "email" : "testEmail1"
    }
  }
}
```

But was:
```json
{
  "data" : {
    "register" : { // extra layer here
      "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI2NTMwNzhjZWNlZWQ5NzJkZjMwMjM5MDMiLCJ1c2VySWQiOiI2NTMwNzhjZWNlZWQ5NzJkZjMwMjM5MDMifQ.68kjUteMAI-Vnz9r8xQlDTqEKFGh34VKy94PH5DXctY",
      "userMinimal" : {
        "id" : "653078ceceed972df3023903",
        "email" : "testEmail1"
      }
    }
  }
}
```

Here is the error, but it only says it could not find the token, which shouldn't be null:
```kotlin
2023-10-19 08:24:29.995 [Test worker @coroutine#1] TRACE i.k.client.plugins.HttpCallValidator - Processing exception io.ktor.serialization.JsonConvertException: Instantiation of [simple type, class com.server.feature.auth.model.AuthResponse] value failed for JSON property token due to missing (therefore NULL) value for creator parameter token which is a non-nullable type
 at [Source: (InputStreamReader); line: 10, column: 3] (through reference chain: com.expediagroup.graphql.server.types.GraphQLResponse["data"]->com.server.feature.auth.model.AuthResponse["token"]) for request http://localhost/graphql

io.ktor.serialization.JsonConvertException: Instantiation of [simple type, class com.server.feature.auth.model.AuthResponse] value failed for JSON property token due to missing (therefore NULL) value for creator parameter token which is a non-nullable type
 at [Source: (InputStreamReader); line: 10, column: 3] (through reference chain: com.expediagroup.graphql.server.types.GraphQLResponse["data"]->com.server.feature.auth.model.AuthResponse["token"])
	at _COROUTINE._BOUNDARY._(CoroutineDebugging.kt:46)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invokeSuspend(HttpCallValidator.kt:142)
	at io.ktor.client.call.HttpClientCall.bodyNullable(HttpClientCall.kt:89)
	at RegisterTests$when register user with email and password then user should be registered$1.invokeSuspend(RegisterTests.kt:95)
	at com.server.helpers.MongoTests$test$1.invokeSuspend(ServerTest.kt:142)
	at io.ktor.server.testing.TestApplicationKt$testApplication$builder$1$1.invokeSuspend(TestApplication.kt:335)
Caused by: io.ktor.serialization.JsonConvertException: Instantiation of [simple type, class com.server.feature.auth.model.AuthResponse] value failed for JSON property token due to missing (therefore NULL) value for creator parameter token which is a non-nullable type
 at [Source: (InputStreamReader); line: 10, column: 3] (through reference chain: com.expediagroup.graphql.server.types.GraphQLResponse["data"]->com.server.feature.auth.model.AuthResponse["token"])
```

Test class I use:
```kotlin
private const val MONGO_CONTAINER = "mongo:4.0.10"
private const val DB_NAME = "test_db"

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
abstract class MongoTests<T : Any> {
    private lateinit var collection: MongoCollection<T>

    private val mongoDBContainer = MongoDBContainer(DockerImageName.parse(MONGO_CONTAINER))
        .waitingFor(org.testcontainers.containers.wait.strategy.Wait.forListeningPort())
        .withReuse(true)

    abstract fun initCollection(database: MongoDatabase): MongoCollection<T>

    @BeforeAll
    fun setup() {
        mongoDBContainer.addExposedPort(27017)
        mongoDBContainer.start()
        val mongoClient = MongoClient.create(mongoDBContainer.connectionString)
        val database = mongoClient.getDatabase(DB_NAME)
        collection = initCollection(database)
        startKoin {
            modules(
                module {
                    factory { mongoClient }
                    single { database }
                },

                authModule,
                userModule,
                messageModule,
                paymentModule,
            )
        }
    }

    @AfterAll
    fun cleanup() {
        runBlocking {
            collection.drop()
        }
        mongoDBContainer.stop()
    }

    @AfterEach
    fun teardown() {
        runBlocking {
            stopKoin()
        }
    }

    fun test(
        users: List<User> = mockUsers,
        query: String,
        operationName: String? = null,
        variables: Map<String, Any?>? = emptyMap(),
        headers: Map<*, Any> = mapOf("id" to user1.id),
        assert: suspend HttpResponse.() -> Unit,
    ) {
        val userRepository: UserRepository by KoinJavaComponent.inject(UserRepository::class.java)

        testApplication {
            application {
                install(io.ktor.server.plugins.contentnegotiation.ContentNegotiation) {
                    jackson {
                        enable(SerializationFeature.INDENT_OUTPUT)
                        setDefaultLeniency(true)
                        registerModules(
                            KotlinModule(
                                nullToEmptyMap = true,
                                nullToEmptyCollection = true,
                            )
                        )
                    }
                }
            }

            users.forEach { userRepository.create(it) }

            val client = getHttpClient()
            val response = client.post("graphql") {
                contentType(ContentType.Application.Json)
                headers.forEach { (key, value) ->
                    header(key.toString(), value.toString())
                }
                setBody(
                    GraphQLRequest(
                        query = query,
                        operationName = operationName,
                        variables = variables,
                    )
                )
            }
            println(response.bodyAsText())

            assert(response)
        }
    }

    context(ApplicationTestBuilder)
    private fun getHttpClient(): HttpClient {
        return createClient {
            install(io.ktor.client.plugins.contentnegotiation.ContentNegotiation) {
                jackson {
                    enable(SerializationFeature.INDENT_OUTPUT)
                    setDefaultLeniency(true)
                    registerModules(
                        KotlinModule(
                            nullToEmptyMap = true,
                            nullToEmptyCollection = true,
                        )
                    )
                }
            }
        }
    }
}

fun Application.testGraphQLModule() {
    configureGraphQL()
    install(io.ktor.server.websocket.WebSockets)
    install(Routing) {
        graphQLGetRoute()
        graphQLPostRoute()
        graphQLSubscriptionsRoute()
        graphQLSDLRoute()
        graphiQLRoute()
    }
}
```

And the test itself:
```kotlin
class RegisterTests : MongoTests<User>() {
    override fun initCollection(database: MongoDatabase): MongoCollection<User> {
        return database.getCollection<User>(User::class.java.simpleName)
    }

    @Test
    fun `when register user with email and password then user should be registered`() = test(
        users = emptyList(),
        query = QUERY,
        operationName = "register",
        variables = mapOf(
            "authInput" to mapOf(
                "email" to user1.email,
                "password" to password1,
            )
        ),
    ) {
        val body = body<GraphQLResponse<AuthResponse>>()
        val expectedUserMinimal = UserMinimal(
            id = user1.id,
            email = user1.email,
            profile = UserProfile(
                username = "",
                fullName = "",
                profilePicture = "",
                messages = emptyList(),
            )
        )

        HttpStatusCode.OK shouldBeEqualTo status
        expectedUserMinimal shouldBeEqualTo body.data?.userMinimal
        body.data?.token?.isNotBlank() shouldBe true
        body.errors shouldBeEqualTo null
    }

   ...
}
```

**Comment by charlee-dev** [comment]
@dariuszkuc Are you on holiday? 😃

**Comment by charlee-dev** [comment]
Closed as confusion was on my side
