### ISSUE TITLE
Unable to perform upgrade as it is not requested by the client: request should have Upgrade and Connection headers filled properly

### ISSUE THREAD

**Issue by charlee-dev** [ExpediaGroup/graphql-kotlin#1901]
**Library Version**
What version are you using?
7.0.2

**Describe the bug**
When trying to start a Subscription on `ws://0.0.0.0:8080/subscriptions` or `http://0.0.0.0:8080/subscriptions` I am getting an error:

```kotlin
2023-12-09 17:38:07.748 [DefaultDispatcher-worker-16] ERROR ktor.application - Unhandled: GET - /subscriptions
java.lang.IllegalStateException: Unable to perform upgrade as it is not requested by the client: request should have Upgrade and Connection headers filled properly
	at io.ktor.server.cio.CIOApplicationResponse.respondOutgoingContent(CIOApplicationResponse.kt:114)
	at io.ktor.server.engine.BaseApplicationResponse$Companion$setupSendPipeline$1.invokeSuspend(BaseApplicationResponse.kt:317)
	at io.ktor.server.engine.BaseApplicationResponse$Companion$setupSendPipeline$1.invoke(BaseApplicationResponse.kt)
	at io.ktor.server.engine.BaseApplicationResponse$Companion$setupSendPipeline$1.invoke(BaseApplicationResponse.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SuspendFunctionGun.kt:88)
	at io.ktor.server.engine.DefaultTransformKt$installDefaultTransformations$1.invokeSuspend(DefaultTransform.kt:29)
	at io.ktor.server.engine.DefaultTransformKt$installDefaultTransformations$1.invoke(DefaultTransform.kt)
	at io.ktor.server.engine.DefaultTransformKt$installDefaultTransformations$1.invoke(DefaultTransform.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
	at io.ktor.server.websocket.RoutingKt.respondWebSocketRaw(Routing.kt:293)
	at io.ktor.server.websocket.RoutingKt.access$respondWebSocketRaw(Routing.kt:1)
	at io.ktor.server.websocket.RoutingKt$webSocketRaw$2$1$1$1.invokeSuspend(Routing.kt:105)
	at io.ktor.server.websocket.RoutingKt$webSocketRaw$2$1$1$1.invoke(Routing.kt)
	at io.ktor.server.websocket.RoutingKt$webSocketRaw$2$1$1$1.invoke(Routing.kt)
	at io.ktor.server.routing.Route$buildPipeline$1$1.invokeSuspend(Route.kt:116)
	at io.ktor.server.routing.Route$buildPipeline$1$1.invoke(Route.kt)
	at io.ktor.server.routing.Route$buildPipeline$1$1.invoke(Route.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
	at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
	at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(Pipeline.kt)
	at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(Pipeline.kt)
	at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
	at io.ktor.server.routing.Routing.executeResult(Routing.kt:190)
	at io.ktor.server.routing.Routing.interceptor(Routing.kt:64)
	at io.ktor.server.routing.Routing$Plugin$install$1.invokeSuspend(Routing.kt:140)
	at io.ktor.server.routing.Routing$Plugin$install$1.invoke(Routing.kt)
	at io.ktor.server.routing.Routing$Plugin$install$1.invoke(Routing.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
	at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invokeSuspend(BaseApplicationEngine.kt:124)
	at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(BaseApplicationEngine.kt)
	at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(BaseApplicationEngine.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
	at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invokeSuspend(DefaultEnginePipeline.kt:123)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invoke(DefaultEnginePipeline.kt)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invoke(DefaultEnginePipeline.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
	at io.ktor.server.cio.CIOApplicationEngine$handleRequest$2$invokeSuspend$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
	at io.ktor.server.cio.CIOApplicationEngine$handleRequest$2$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
	at io.ktor.server.cio.CIOApplicationEngine$handleRequest$2$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
	at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
	at io.ktor.server.cio.CIOApplicationEngine$handleRequest$2.invokeSuspend(CIOApplicationEngine.kt:239)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2023-12-09 17:38:07.749 [DefaultDispatcher-worker-16] INFO  ktor.application - 500 Internal Server Error: GET - /subscriptions in 2ms
```

**Expected behavior**
I expect subscription started?

**To Reproduce**
Steps to reproduce the behavior. Please provide:

#### Routing
```kotlin
install(Routing) {
        graphQLPostRoute()
        graphQLGetRoute()
        graphQLSubscriptionsRoute()
        graphiQLRoute()
        graphQLSDLRoute()

        get("apollo") {
            this.call.respondText(
                buildPlaygroundHtml("graphql-apollo.html"),
                ContentType.Text.Html,
            )
        }
        get("playground") {
            this.call.respondText(
                buildPlaygroundHtml("graphql-playground.html"),
                ContentType.Text.Html,
            )
        }
    }
```

#### Schema
```kotlin
install(GraphQL) {
        schema {
            packages = listOf(
                "$PACKAGE_NAME.model",
                "$PACKAGE_NAME.usecase",
            )
            queries = listOf(
                DebugSchema.Queries(),
                ForgotPasswordQuery,
                GetUserQuery,
                GetUserByIdQuery,
                GetMatchersPageQuery,
                GetMatchedLikesWithoutConversationQuery,
                GetConversationsPageQuery,
                GetMessagesPageQuery,
            )

            mutations = listOf(
                DebugSchema.Mutations(),
                LoginMutation,
                RegisterMutation,
                UpdateUserMutation,
                SaveSwipeMutation,
                CreateConversationMutation,
                SendMessageMutation,
            )

            subscriptions = listOf(
                WatchConversationsSubscription,
            )

            schemaObject = ForevelySchema()
            hooks = CustomSchemaGeneratorHooks()
        }
        server {
            contextFactory = CustomGraphQLContextFactory()
            jacksonConfiguration = {
                enable(SerializationFeature.INDENT_OUTPUT)
                setDefaultLeniency(true)
                registerModules(
                    KotlinModule(
                        nullToEmptyMap = true,
                        nullToEmptyCollection = true,
                    ),
                )
            }
            requestParser = KtorGraphQLRequestParser(jacksonObjectMapper().apply(jacksonConfiguration))
        }
    }
```

#### Context

```kotlin
class CustomGraphQLContextFactory : DefaultKtorGraphQLContextFactory(), KoinComponent {
    private val jwtService: JwtService by inject()

    override suspend fun generateContext(request: ApplicationRequest): graphql.GraphQLContext =
        super.generateContext(request).plus(
            mutableMapOf(
                "Access-Control-Allow-Origin" to "*",
                "Access-Control-Allow-Methods" to "*",
                "Access-Control-Allow-Credentials" to "true",
                "Access-Control-Allow-Headers" to
                    "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since," +
                    "Cache-Control,Content-Type,Content-Range,Range",
                "Access-Control-Expose-Headers" to
                    "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since," +
                    "Cache-Control,Content-Type,Content-Range,Range",
                "id" to request.getUserIdFromAuthHeader(),
            ),
        )

    private fun ApplicationRequest.getUserIdFromAuthHeader(): String {
        val token = headers[HttpHeaders.Authorization]
        val userId = token?.let { jwtService.verifyToken(it) }
        userId?.let { it.ifBlank { throw GraphQLException(ErrorMessage.TOKEN_FAILED_DECODE) } }
        return userId ?: ""
    }
}
```

#### Subscription
```kotlin
object WatchConversationsSubscription : Subscription {
    private val database by KoinJavaComponent.inject<MongoDatabase>(MongoDatabase::class.java)
    private val conversationCollection = database.getCollection<Conversation>(Conversation::class.java.simpleName)
    private val messageCollection = database.getCollection<Message>(Message::class.java.simpleName)
    private val userCollection = database.getCollection<User>(User::class.java.simpleName)

    @Suppress("unused")
    @GraphQLDescription("Watch for new messages in conversations")
    suspend fun watchConversations(
        dfe: DataFetchingEnvironment,
    ): Flow<NewMessage> = flow {
        dfe.withCurrentUser { currentUserId -> // It cannot find user here
            val filter = Filters.`in`(Conversation::participantIds.name, currentUserId)
            val pipeline = listOf(Aggregates.match(filter))

            conversationCollection.watch(pipeline)
                .fullDocument(FullDocument.DEFAULT)
                .collect {
                    when (it.operationType) {
                        OperationType.UPDATE -> {
                            val updatedFields = it.updateDescription?.updatedFields
                            if (updatedFields?.contains(Conversation::lastMessageTimestamp.name) == true) {
                                it.fullDocument?.let { conversation ->
                                    val message =
                                        messageCollection.find(Filters.eq(OBJECT_ID, conversation.messageIds.last()))
                                            .first()

                                    val senderName = getMatcherName(message.senderId)

                                    val newMessage = NewMessage(
                                        senderName = senderName,
                                        message = message,
                                    )
                                    emit(newMessage)
                                }
                            }
                        }

                        else -> {
                            // do nothing?
                        }
                    }
                }
        }

    ...
}
```

#### WithCurrentUser
```kotlin
suspend fun <T> DataFetchingEnvironment.withCurrentUser(block: suspend (userId: ObjectId) -> T): T {
    val id = graphQlContext.get<String>("id") ?: throw GraphQLException(ErrorMessage.NOT_SIGNED_IN)
    val objectId = ObjectId(id)
    return block(objectId)
}
```

#### Query
```kotlin
subscription WatchConversations {
  watchConversations {
    senderName
    message {
      content
      conversationId
      id
      senderId
      timestamp
    }
  }
}

// Header
{
  "Authorizartion": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI2NTcyZTE3MjA0YWRlMzU4MTU2ZjkzYmQiLCJ1c2VySWQiOiI2NTcyZTE3MjA0YWRlMzU4MTU2ZjkzYmQifQ.ChawrcUAEytxhG_rUA3UCmAMf5NmL_3zDWVLfp-SYNY"
}
```

#### Postman
![CleanShot 2023-12-09 at 17 40 11](https://github.com/ExpediaGroup/graphql-kotlin/assets/20965327/a3213638-a69f-4efa-adc6-ac010a2690b9)

#### GralhiQL
![CleanShot 2023-12-09 at 17 53 11](https://github.com/ExpediaGroup/graphql-kotlin/assets/20965327/25463f4a-8f26-4d76-9ef7-d69b7208e531)

**Comment by charlee-dev** [comment]
Managed to get is working. Closing
