### ISSUE TITLE
Circular class references cause StackOverflowError on InputType generation

### ISSUE THREAD

**Issue by cwendel16834** [ExpediaGroup/graphql-kotlin#527]
**Library Version**
1.4.2

**Describe the bug**
Circular class references are explicitly supported by GraphQL and graphql-kotlin. They appear to work fine when generating the GraphQLType, but fail when generating a GraphQLInputType for the same object. Once a class with a circular reference is introduced to the schema as an input to a Query, the schema generation loops while generating the input type and crashes with a StackOverflowError.

**To Reproduce**
Steps to reproduce the behavior. Please provide:
1. Add a circular reference to a class picked up for schema generation. The simplest way to do this is to add a property of the same type to the class. See example below.
2. Add a query funcition that accepts this class as a parameter
3. Generate schema and notice the output loops and overflows

Minimal repro project available here: https://github.com/cwendel16834/graphqlbugrepro

Repro code
```
class Person {
    val friend: Person = Person()
}

@Component
class Queries : Query {
    fun getPerson(): Person = TODO()

    // Comment this line and it works
    fun addPerson(inputPerson: Person): String = TODO()
}
````

Here is a sample of the output stack trace:
```
at com.expediagroup.graphql.generator.types.InputPropertyBuilder.inputProperty$graphql_kotlin_schema_generator(InputPropertyBuilder.kt:37) ~[graphql-kotlin-schema-generator-1.4.2.jar:na]
	at com.expediagroup.graphql.generator.SchemaGenerator.inputProperty(SchemaGenerator.kt:114) ~[graphql-kotlin-schema-generator-1.4.2.jar:na]
	at com.expediagroup.graphql.generator.types.InputObjectBuilder.inputObjectType$graphql_kotlin_schema_generator(InputObjectBuilder.kt:41) ~[graphql-kotlin-schema-generator-1.4.2.jar:na]
	at com.expediagroup.graphql.generator.SchemaGenerator.inputObjectType(SchemaGenerator.kt:111) ~[graphql-kotlin-schema-generator-1.4.2.jar:na]
	at com.expediagroup.graphql.generator.TypeBuilder.getGraphQLType(TypeBuilder.kt:84) ~[graphql-kotlin-schema-generator-1.4.2.jar:na]
	at com.expediagroup.graphql.generator.TypeBuilder.objectFromReflection(TypeBuilder.kt:67) ~[graphql-kotlin-schema-generator-1.4.2.jar:na]
	at com.expediagroup.graphql.generator.TypeBuilder.graphQLTypeOf$graphql_kotlin_schema_generator(TypeBuilder.kt:46) ~[graphql-kotlin-schema-generator-1.4.2.jar:na]
	at com.expediagroup.graphql.generator.types.InputPropertyBuilder.inputProperty$graphql_kotlin_schema_generator(InputPropertyBuilder.kt:37) ~[graphql-kotlin-schema-generator-1.4.2.jar:na]
	at com.expediagroup.graphql.generator.SchemaGenerator.inputProperty(SchemaGenerator.kt:114) ~[graphql-kotlin-schema-generator-1.4.2.jar:na]
	at com.expediagroup.graphql.generator.types.InputObjectBuilder.inputObjectType$graphql_kotlin_schema_generator(InputObjectBuilder.kt:41) ~[graphql-kotlin-schema-generator-1.4.2.jar:na]
	at com.expediagroup.graphql.generator.SchemaGenerator.inputObjectType(SchemaGenerator.kt:111) ~[graphql-kotlin-schema-generator-1.4.2.jar:na]
	at com.expediagroup.graphql.generator.TypeBuilder.getGraphQLType(TypeBuilder.kt:84) ~[graphql-kotlin-schema-generator-1.4.2.jar:na]
	at com.expediagroup.graphql.generator.TypeBuilder.objectFromReflection(TypeBuilder.kt:67) ~[graphql-kotlin-schema-generator-1.4.2.jar:na]
	at com.expediagroup.graphql.generator.TypeBuilder.graphQLTypeOf$graphql_kotlin_schema_generator(TypeBuilder.kt:46) ~[graphql-kotlin-schema-generator-1.4.2.jar:na]
	at com.expediagroup.graphql.generator.types.InputPropertyBuilder.inputProperty$graphql_kotlin_schema_generator(InputPropertyBuilder.kt:37) ~[graphql-kotlin-schema-generator-1.4.2.jar:na]
```

**Expected behavior**
Circular references should work on InputTypes the same way they work on normal generated Types. They should not fail to generate.

**Comment by smyrick** [comment]
Thank you for reporting this bug. This is indeed a valid issue. I have found a fix stepping through your provided test cases. I will put together a PR for review.
