### ISSUE TITLE
DataFetchingException: Object is not an instance of declaring class

### ISSUE THREAD

**Issue by sinwailam193** [ExpediaGroup/graphql-kotlin#730]
**Library Version**
"com.expediagroup:graphql-kotlin-spring-server:2.1.1"

**Describe the bug**
I'm currently using spring webflux and spring server auto config package with graphql-kotlin, I am returning an instance of a class and it would work fine, but when I make changes or any changes for that matter, I would get these errors:
![image](https://user-images.githubusercontent.com/8454621/83224922-2e856980-a1b1-11ea-81ac-833db4941864.png)
I'm currently using spring-devtool and every time I make a change, it would build the file in intellij ide. This issue doesn't occur when I just stop and rebuild the entire server. Just wondering if this is a known issue or is it just me? 

**To Reproduce**
Steps to reproduce the behavior. Please provide:
This is my sample code, which is very basic:
![image](https://user-images.githubusercontent.com/8454621/83225021-6b516080-a1b1-11ea-8b95-f46a4034c707.png)
Then go ahead and make any changes or add a println, then hit build in which devtool should kick in and reload the changes. Then if you fetch for the data again in playground, it will produce this issue.

**Expected behavior**
This should happen: 
![image](https://user-images.githubusercontent.com/8454621/83225211-d56a0580-a1b1-11ea-8c4d-0330399d313c.png)

But if I make any changes and the code get build with spring devtool, the second time I run it again, I would get this "Object is not an instance of declaring class". Btw, love the library and it's been awesome running with it, just wondering if this is an issue with spring-devtool

**Comment by sinwailam193** [comment]
as I dug deeper, it has to deal with hot reloading https://github.com/leangen/graphql-spqr/issues/259. Will close this issue

**Comment by dariuszkuc** [comment]
This issue does not seem to be related to the library functionality but appears to be an issue with hot-swapping (https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto-hotswapping). I believe `spring-devtool` helps with reloading static templates but unsure whether it helps with hot-swapping modified classes.

**Comment by sinwailam193** [comment]
Thanks for the comment, but do no one else uses `spring-devtool` along with `graphql-kotlin-spring-server` or is it just me? If someone knows of a way to fix this, it would be highly appreciated.

**Comment by sinwailam193** [comment]
> This issue does not seem to be related to the library functionality but appears to be an issue with hot-swapping (https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto-hotswapping). I believe `spring-devtool` helps with reloading static templates but unsure whether it helps with hot-swapping modified classes.

Hi just curious, could it be related to the classes being deserialized? https://docs.spring.io/spring-boot/docs/1.5.16.RELEASE/reference/html/using-boot-devtools.html#using-boot-devtools-known-restart-limitations

**Comment by stevefan1999-personal** [comment]
Yes, this is pretty annoying. It seems like graphql-kotlin does not account for the new context loader created by spring boot, and therefore still references the old context loader which is obviously destroyed.

Here's one of my stack trace:

```
java.lang.IllegalArgumentException: object is not an instance of declaring class
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at graphql.schema.PropertyDataFetcherHelper.getPropertyViaGetterUsingPrefix(PropertyDataFetcherHelper.java:133) ~[graphql-java-15.0.jar:na]
	at graphql.schema.PropertyDataFetcherHelper.getPropertyViaGetterMethod(PropertyDataFetcherHelper.java:119) ~[graphql-java-15.0.jar:na]
	at graphql.schema.PropertyDataFetcherHelper.getPropertyValue(PropertyDataFetcherHelper.java:60) ~[graphql-java-15.0.jar:na]
	at graphql.schema.PropertyDataFetcher.get(PropertyDataFetcher.java:120) ~[graphql-java-15.0.jar:na]
	at graphql.execution.instrumentation.dataloader.DataLoaderDispatcherInstrumentation.lambda$instrumentDataFetcher$0(DataLoaderDispatcherInstrumentation.java:86) ~[graphql-java-15.0.jar:na]
	at graphql.execution.instrumentation.dataloader.DataLoaderDispatcherInstrumentation$$Lambda$931/0000000056AEFB80.get(Unknown Source) ~[na:na]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:277) ~[graphql-java-15.0.jar:na]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:202) ~[graphql-java-15.0.jar:na]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:74) ~[graphql-java-15.0.jar:na]
	at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:659) ~[graphql-java-15.0.jar:na]
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:443) ~[graphql-java-15.0.jar:na]
	at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:393) ~[graphql-java-15.0.jar:na]
	at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$0(ExecutionStrategy.java:204) ~[graphql-java-15.0.jar:na]
	at graphql.execution.ExecutionStrategy$$Lambda$858/0000000057001710.apply(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2158) ~[na:na]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:203) ~[graphql-java-15.0.jar:na]
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:175) ~[graphql-java-15.0.jar:na]
	at graphql.execution.AsyncSerialExecutionStrategy.lambda$execute$1(AsyncSerialExecutionStrategy.java:41) ~[graphql-java-15.0.jar:na]
	at graphql.execution.AsyncSerialExecutionStrategy$$Lambda$929/0000000056551920.apply(Unknown Source) ~[na:na]
	at graphql.execution.Async.eachSequentiallyImpl(Async.java:77) ~[graphql-java-15.0.jar:na]
	at graphql.execution.Async.eachSequentially(Async.java:66) ~[graphql-java-15.0.jar:na]
	at graphql.execution.AsyncSerialExecutionStrategy.execute(AsyncSerialExecutionStrategy.java:36) ~[graphql-java-15.0.jar:na]
	at graphql.execution.Execution.executeOperation(Execution.java:167) ~[graphql-java-15.0.jar:na]
	at graphql.execution.Execution.execute(Execution.java:108) ~[graphql-java-15.0.jar:na]
	at graphql.GraphQL.execute(GraphQL.java:598) ~[graphql-java-15.0.jar:na]
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:529) ~[graphql-java-15.0.jar:na]
	at graphql.GraphQL.executeAsync(GraphQL.java:493) ~[graphql-java-15.0.jar:na]
	at com.expediagroup.graphql.spring.execution.SimpleQueryHandler.executeQuery$suspendImpl(QueryHandler.kt:55) ~[graphql-kotlin-spring-server-3.6.2.jar:3.6.2]
	at com.expediagroup.graphql.spring.execution.SimpleQueryHandler.executeQuery(QueryHandler.kt) ~[graphql-kotlin-spring-server-3.6.2.jar:3.6.2]
	at com.expediagroup.graphql.spring.RoutesConfiguration$graphQLRoutes$1$1.invokeSuspend(RoutesConfiguration.kt:69) ~[graphql-kotlin-spring-server-3.6.2.jar:3.6.2]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.4.10.jar:1.4.10-release-411 (1.4.10)]
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:175) ~[kotlinx-coroutines-core-1.3.8.jar:na]
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:137) ~[kotlinx-coroutines-core-1.3.8.jar:na]
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:108) ~[kotlinx-coroutines-core-1.3.8.jar:na]
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:308) ~[kotlinx-coroutines-core-1.3.8.jar:na]
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:318) ~[kotlinx-coroutines-core-1.3.8.jar:na]
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:250) ~[kotlinx-coroutines-core-1.3.8.jar:na]
	at kotlinx.coroutines.reactive.AwaitKt$awaitOne$$inlined$suspendCancellableCoroutine$lambda$1.onComplete(Await.kt:133) ~[kotlinx-coroutines-reactive-1.3.8.jar:na]
	at reactor.core.publisher.StrictSubscriber.onComplete(StrictSubscriber.java:123) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onComplete(FluxContextStart.java:115) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2016) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2016) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1783) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:287) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:330) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:152) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
	at reactor.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:445) ~[reactor-netty-0.9.10.RELEASE.jar:0.9.10.RELEASE]
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:251) ~[reactor-netty-0.9.10.RELEASE.jar:0.9.10.RELEASE]
	at reactor.netty.channel.FluxReceive.lambda$request$1(FluxReceive.java:135) ~[reactor-netty-0.9.10.RELEASE.jar:0.9.10.RELEASE]
	at reactor.netty.channel.FluxReceive$$Lambda$817/0000000056D7E7C0.run(Unknown Source) ~[na:na]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.51.Final.jar:4.1.51.Final]
	at java.base/java.lang.Thread.run(Thread.java:851) ~[na:na]
```

**Comment by Szer** [comment]
@dariuszkuc ^^

**Comment by Szer** [comment]
Found a workaround.
Create "fixed" PropertyDataFetcher:
```kotlin
class AsyncPropertyDataFetcher(private val propertyGetter: KProperty.Getter<*>) : DataFetcher<Any?> {
    override fun get(environment: DataFetchingEnvironment): Any? = environment.getSource<Any?>()?.let { instance ->
        Async.toCompletableFuture(instance).thenApply {
            propertyGetter.call(it)
        }
    }
}
```

Create your own `KotlinDataFetcherFactoryProvider`: copy everything from `SimpleKotlinDataFetcherFactoryProvider`, with new property fetcher:
```kotlin
    override fun propertyDataFetcherFactory(kClass: KClass<*>, kProperty: KProperty<*>) = DataFetcherFactory {
        AsyncPropertyDataFetcher(kProperty.getter)
    }
    ```
Pass it to `SchemaGeneratorConfig` or to `FederatedSchemaGeneratorHooks`
Profit!

**Comment by dariuszkuc** [comment]
Somewhat curious on your use case for custom property data fetcher - if it is a property on an object unsure why you ever wrap it as a future?

e.g.
```kotlin
data class Foo(val myFuture: CompletableFuture<String>)

// vs resolving Foo async and returning actual values
data class Foo(val stringValue: String)
```

**Comment by Szer** [comment]
@dariuszkuc I'm using custom directive for "per-field" authentication (different auth schemas for different queries), so whenever the field is being fetched, some behind-the-scenes logic with async calls to Identity Providers will happen.

But field itself shouldn't be wrapped in `CompletableFuture`

**Comment by dariuszkuc** [comment]
Can you provide a repo that reproduces this issue?

**Comment by Szer** [comment]
Sure thing. Will try to provide repro in 24hrs.

**Comment by Szer** [comment]
@dariuszkuc repro
https://github.com/Szer/graphql-async-fetcher-repro

Just run it and you will see an error.

Workaround (any will work)
- change request to be `query{auth2{token}}`. The only difference between `auth1` and `auth2` is that `auth1` suspended function https://github.com/Szer/graphql-async-fetcher-repro/blob/050144a25b555aa0124c4c99c1a0382532bb2f93/app/src/main/kotlin/graphql/async/fetcher/repro/TopQuery.kt#L12-L22
- uncomment this line to use PropertyFetcher which can work with CompletableFuture https://github.com/Szer/graphql-async-fetcher-repro/blob/050144a25b555aa0124c4c99c1a0382532bb2f93/app/src/main/kotlin/graphql/async/fetcher/repro/App.kt#L36

**Comment by dariuszkuc** [comment]
@Szer apologies for the delay in the response.

Underlying issue in your repro is that you are attempting to return a future of a future - i.e. your custom auth resolver from a directive always attempts to return a future, i.e.

* It works for `fun auth2(): Response` as it ends up returning `CompletableFuture<Response>`
* It blows up for `suspend fun auth1(): Response` as default `FunctionDataFetcher` wraps the coroutine call in the future (https://github.com/ExpediaGroup/graphql-kotlin/blob/master/generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/FunctionDataFetcher.kt#L173) so your custom auth resolver then attempts to return `CompletableFuture<CompletableFuture<Response>>`.

If you move your auth directive on the field itself (fields by default are resolved by `PropertyDataFetcher` which issues just a getter call on the underlying field) then it still should work as your custom auth resolver wraps target field type in `CompletableFuture` which again is a valid return type. I'd recommend to update your custom auth resolver to account for the return type from the original data fetcher (i.e. don't wrap future in another future).
