### ISSUE TITLE
[Classpath Issue] There is a major classpath issue in GraphQLKtorClient module Version 4.0.0-alpha.7

### ISSUE THREAD

**Issue by ubarua123** [ExpediaGroup/graphql-kotlin#923]
Issue: 
### [NoSuchMethodError] io.ktor.http.URLUtilsJvmKt.takeFrom

The Stack trace looks like this:
```
java.lang.NoSuchMethodError: io.ktor.http.URLUtilsJvmKt.takeFrom(Lio/ktor/http/URLBuilder;Ljava/net/URL;)V
	at com.expediagroup.graphql.client.GraphQLKtorClient.execute$suspendImpl(GraphQLKtorClient.kt:128)
	at com.expediagroup.graphql.client.GraphQLKtorClient.execute(GraphQLKtorClient.kt)
	at com.muuzzer.web.graphql.FetchSingle.execute(GetSingleContent.kt:174)
	at com.muuzzer.web.graphql.FetchSingle.execute$default(GetSingleContent.kt:23)
```

The particular line is where it makes the post request. It's a harmless post request, but somehow the runtime environment is unable to locate the `URLUtilsJvm.kt` class. The compiler compiles properly. This file is part of the library `ktor-client-core-jvm`

My dependancies when I ran into this issue:
```
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation "io.ktor:ktor-server-netty:$ktor_version"
    implementation "ch.qos.logback:logback-classic:$logback_version"
    implementation "io.ktor:ktor-server-core:$ktor_version"
    implementation "io.ktor:ktor-thymeleaf:$ktor_version"
    implementation "io.ktor:ktor-jackson:$ktor_version"
    implementation "io.ktor:ktor-client-core:$ktor_version"
    implementation "io.ktor:ktor-client-core-jvm:$ktor_version"
    implementation "io.ktor:ktor-client-cio-jvm:$ktor_version"
    implementation "io.ktor:ktor-client-jackson:$ktor_version"
    implementation "io.ktor:ktor-client-json-jvm:$ktor_version"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:$jackson_jsr310"
    // Koin for Ktor Kotlin
    implementation "org.koin:koin-ktor:$ktor_koin"
    // Koin Extended & experimental features
    implementation "org.koin:koin-core-ext:$ktor_koin"
    api "org.koin:koin-logger-slf4j:$ktor_koin"

   implementation("com.expediagroup:graphql-kotlin-ktor-client:$ktor_graphql_client")
```

```
ktor_version=1.4.1
ktor_graphql_client=4.0.0-alpha.7
```

#### Workaround?
I copied all the classes `GraphQLKtorClient` and related from the 3 modules it depends on, AND the generated classes, and now it works. So clearly the classpath is proper in my project but there is some issue in the library

**Comment by dariuszkuc** [comment]
Hello 👋 
In general `NoSuchMethodError` implies version mismatch of some library on the classpath. My guess is this is because `graphql-kotlin-ktor-clients` uses ktor v1.3.1 and you are adding dependencies on v1.4.1

**Comment by ubarua123** [comment]
Yeah that's what. Guess We'll have to wait for the next release when they update the dependancy
